# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Handler\Error\ErrorHandlerInterface:
            tags: ['app.handlers.error']
        App\Handler\Request\TransformationHandlerInterface:
            tags: ['app.handlers.request.transformation']
        App\Service\Statement\Import\Handler\StatementImportHandlerInterface:
            tags: ['app.statement.import.handlers']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Exception'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\EventListener\CalendarBalanceListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: postUpdate, entity: App\Entity\Expense }
            - { name: doctrine.orm.entity_listener, event: postPersist, entity: App\Entity\Expense }
            - { name: doctrine.orm.entity_listener, event: postRemove, entity: App\Entity\Expense }
