services:
  application:
    image: algirdasc/expensave
    restart: unless-stopped
    ports:
      - "80:18000"
    env_file:
      - environment
    depends_on:
      - database
    # docker exec -it expensave-application-1 php bin/console doctrine:migrations:migrate -n

  queue:
    image: algirdasc/expensave
    command: php bin/console messenger:consume --all -v
    restart: unless-stopped
    env_file:
      - environment
    depends_on:
      - application

  database:
    image: mariadb:10.6
    volumes:
      - './db:/var/lib/mysql'
    restart: unless-stopped
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_USER: expensave
      MARIADB_PASSWORD: expensave
      MARIADB_DATABASE: expensave
