services:
  dev-backend:
    build:
      target: development-backend
    volumes:
      - '.:/opt/expensave'
    environment:
      LOCALE: en
      TZ: Europe/Vilnius
      REGISTRATION_DISABLED: no
      DATABASE_NAME: dev-expensave
      DATABASE_USER: dev-expensave
      DATABASE_PASS: dev-expensave
      DATABASE_HOST: dev-database
    depends_on:
      - dev-database
    ports:
      - 18001:18001

  dev-frontend:
    build:
      target: development-frontend
    environment:
      LOCALE: en
      REGISTRATION_DISABLED: no
    volumes:
      - '.:/opt/expensave'
    ports:
      - 18002:18002

  dev-database:
    image: mariadb:10.6
    volumes:
      - './backend/var/db:/var/lib/mysql'
      - './docker/mariadb/development.init.sql:/docker-entrypoint-initdb.d/init.sql'
    restart: unless-stopped
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_USER: dev-expensave
      MARIADB_PASSWORD: dev-expensave
      MARIADB_DATABASE: dev-expensave
    ports:
      - 3306:3306
