name: "Code quality"

on:
  - workflow_call
  - push
  - pull_request

jobs:
  code-quality:
    name: Code quality checks
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'backend/'
          sparse-checkout-cone-mode: false
      - name: Move backend to root
        run: |
          shopt -s dotglob
          mv backend/* ./
          rm -rf backend/
          mkdir -p var/cache
      - name: Composer
        uses: php-actions/composer@v6
        with:
          args: --profile --ignore-platform-reqs
      - name: Run PHPStan
        uses: php-actions/phpstan@v3
      - name: Run PHPCS
        uses: php-actions/phpcs@v1
        with:
          path: ./src/
          args: -d memory_limit=-1
      - name: Run PHPUnit
        uses: php-actions/phpunit@v3
        with:
          php_extensions: "xdebug"
#          coverage_clover: "coverage/clover.xml"