name: "Code quality"

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm check
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Psalm check
        uses: docker://ghcr.io/psalm/psalm-github-actions
        with:
          relative_dir: ./backend
          security_analysis: true
          composer_ignore_platform_reqs: true
#          report_file: results.sarif
#      - name: Upload Security Analysis results to GitHub
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: results.sarif

  phpcs:
    name: PHPCS check
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Composer
        uses: php-actions/composer@v6
        with:
          args: --profile --ignore-platform-reqs
          working_dir: ./backend
      - name: PHPCS
        uses: php-actions/phpcs@v1
        with:
          path: ./backend
          args: -d memory_limit=-1
 
  phpunit:
    name: PHPUnit tests
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Composer
        uses: php-actions/composer@v6
        with:
          args: --profile --ignore-platform-reqs
          working_dir: ./backend
      - name: PHPUnit
        uses: php-actions/phpunit@v3
        with:
          php_extensions: "xdebug"
          args: ./backend
#          coverage_clover: "coverage/clover.xml"