name: "Code quality"

on: [push, pull_request]

jobs:
  psalm:
    name: PHPStan check
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'backend/'
          sparse-checkout-cone-mode: false
      - name: Move backend to root
        run: |
          ls -lah
          mv backend/* .
          rm -rf backend/
          ls -lah
      - name: Composer
        uses: php-actions/composer@v6
        with:
          args: --profile --ignore-platform-reqs
          working_dir: ./
      - name: Run PHPStan
        uses: php-actions/phpstan@v3

  phpcs:
    name: PHPCS check
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Composer
        uses: php-actions/composer@v6
        with:
          args: --profile --ignore-platform-reqs
          working_dir: ./backend
      - name: Run PHPCS
        uses: php-actions/phpcs@v1
        with:
          basepath: ./backend/
          path: ./backend/src/
          args: -d memory_limit=-1
 
  phpunit:
    name: PHPUnit tests
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Composer
        uses: php-actions/composer@v6
        with:
          args: --profile --ignore-platform-reqs
          working_dir: ./backend
      - name: Run PHPUnit
        uses: php-actions/phpunit@v3
        with:
          php_extensions: "xdebug"
          configuration: ./backend/phpunit.xml.dist
          args: ./backend
#          coverage_clover: "coverage/clover.xml"