name: "Code quality"

on: [push, pull_request]

jobs:
  psalm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://ghcr.io/psalm/psalm-github-actions
        with:
          relative_dir: ./backend
          security_analysis: true
          composer_ignore_platform_reqs: true
#          report_file: results.sarif
#      - name: Upload Security Analysis results to GitHub
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: results.sarif

  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          args: --profile --ignore-platform-reqs
          working_dir: ./backend
      - uses: php-actions/phpcs@v1
        with:
          path: ./backend

  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          args: --profile --ignore-platform-reqs
          working_dir: ./backend
      - uses: php-actions/phpunit@v3
        with:
          php_extensions: "xdebug"
#          coverage_clover: "coverage/clover.xml"